Repository landinfotech/mycivitas, pull requests merged in 2024-03, with the labels that each got.

#84 Update the landing page manual
  docs/src/user/manual/img/landing-page-1.png
  docs/src/user/manual/img/landing-page-15.png
  docs/src/user/manual/img/sign-up-2.png
  docs/src/user/manual/img/sign-up-4.png
  docs/src/user/manual/landing-page.md
  docs/src/user/manual/sign-up.md
Labels: documentation, 2

#85 Improve the user guide registration page doc
  docs/src/user/guide/img/register-login-logout-2.png
  docs/src/user/guide/register-login-logout.md
Labels: documentation, 1

#86 Improve organisation guide
  docs/src/user/guide/organisation.md
Labels: documentation, 1

#87 Add contributor
  docs/src/about/index.md
  docs/src/about/running-instances.md
Labels: documentation, 1

#90 Multiple improvements
  docs/src/img/scope-1.png
  docs/src/index.md
Labels: documentation

#91 Add user role documentation
  docs/src/user/manual/img/user-role-1.png
  docs/src/user/manual/img/user-role-2.png
  docs/src/user/manual/img/user-role-3.png
  docs/src/user/manual/img/user-role-4.png
  docs/src/user/manual/img/user-role-5.png
  docs/src/user/manual/user-role.md
Labels: documentation, 5

#96 Developer guide writing documentation
  docs/src/developer/documentation/context-help.md
  docs/src/developer/documentation/easy-workflow.md
  docs/src/developer/documentation/img/check-branch.png
  docs/src/developer/documentation/img/context-help-1.png
  docs/src/developer/documentation/img/context-help-10.png
  docs/src/developer/documentation/img/context-help-11.png
  docs/src/developer/documentation/img/context-help-12.png
  docs/src/developer/documentation/img/context-help-13.png
  docs/src/developer/documentation/img/context-help-14.png
  docs/src/developer/documentation/img/context-help-15.png
  docs/src/developer/documentation/img/context-help-16.png
  docs/src/developer/documentation/img/context-help-17.png
  docs/src/developer/documentation/img/context-help-2.png
  docs/src/developer/documentation/img/context-help-3.png
  docs/src/developer/documentation/img/context-help-4.png
  docs/src/developer/documentation/img/context-help-5.png
  docs/src/developer/documentation/img/context-help-6.png
  docs/src/developer/documentation/img/context-help-7.png
  docs/src/developer/documentation/img/context-help-8.png
  docs/src/developer/documentation/img/context-help-9.png
  docs/src/developer/documentation/img/fork-repo-1.png
  docs/src/developer/documentation/img/fork-repo-2.png
  docs/src/developer/documentation/img/pull-request-1.png
  docs/src/developer/documentation/img/pull-request-2.png
  docs/src/developer/documentation/img/web-editor-1.png
  docs/src/developer/documentation/img/web-editor-2.png
  docs/src/developer/documentation/img/web-editor-3.png
  docs/src/developer/documentation/img/web-editor-4.png
  docs/src/developer/documentation/img/web-editor-5.png
  docs/src/developer/documentation/img/web-editor-6.png
  docs/src/developer/documentation/img/web-editor-7.png
  docs/src/developer/documentation/overview.md
Labels: documentation, 5

#100 Administration user guide
  docs/mkdocs-base.yml
  docs/src/administrator/guide/access-admin-site.md
  docs/src/administrator/guide/img/accessing-admin-site-1.png
  docs/src/administrator/guide/img/accessing-admin-site-2.png
  docs/src/administrator/guide/img/accessing-admin-site-3.png
  docs/src/administrator/guide/img/accessing-admin-site-4.png
  docs/src/administrator/guide/img/accessing-admin-site-5.png
  docs/src/administrator/guide/img/accessing-admin-site-6.png
  docs/src/administrator/guide/index.md
Labels: documentation, 3

#102 Documentation forgot password
  docs/mkdocs-base.yml
  docs/src/user/guide/forgot-password.md
  docs/src/user/guide/img/forgot-password-1.png
  docs/src/user/guide/img/forgot-password-2.png
  docs/src/user/guide/img/forgot-password-3.png
  docs/src/user/guide/img/forgot-password-4.png
  docs/src/user/guide/img/forgot-password-5.png
  docs/src/user/guide/img/forgot-password-6.png
  docs/src/user/guide/img/forgot-password-7.png
  docs/src/user/guide/img/register-login-logout-5.png
  docs/src/user/guide/index.md
  docs/src/user/guide/register-login-logout.md
  docs/src/user/manual/forgot-password.md
  docs/src/user/manual/img/forgot-password-1.png
  docs/src/user/manual/img/forgot-password-2.png
  docs/src/user/manual/img/forgot-password-3.png
  docs/src/user/manual/img/forgot-password-4.png
  docs/src/user/manual/img/forgot-password-5.png
  docs/src/user/manual/img/forgot-password-6.png
  docs/src/user/manual/img/forgot-password-7.png
  docs/src/user/manual/img/sign-in-2.png
  docs/src/user/manual/index.md
  docs/src/user/manual/sign-in.md
Labels: documentation, 8

#94 Developer documentation
  docs/mkdocs-base.yml
  docs/src/developer/guide/architecture.md
  docs/src/developer/guide/building.md
  docs/src/developer/guide/cloning.md
  docs/src/developer/guide/configuration.md
  docs/src/developer/guide/design.md
  docs/src/developer/guide/ide-setup.md
  docs/src/developer/guide/img/architecture-backbone-js-icon.svg
  docs/src/developer/guide/img/architecture-gdal.png
  docs/src/developer/guide/img/architecture-material-ui.svg
  docs/src/developer/guide/img/architecture-tegola.png
  docs/src/developer/guide/index.md
  docs/src/developer/guide/prerequisites.md
  docs/src/developer/guide/roadmap.md
  docs/src/developer/guide/templates/commit-message-convention.md
  docs/src/developer/guide/templates/pull-request-template.md
  docs/src/developer/guide/workflows.md
Labels: documentation, 8

#104 Administrations table guide
  docs/mkdocs-base.yml
  docs/src/administrator/guide/img/manage-user-1.png
  docs/src/administrator/guide/img/manage-user-10.png
  docs/src/administrator/guide/img/manage-user-11.png
  docs/src/administrator/guide/img/manage-user-12.png
  docs/src/administrator/guide/img/manage-user-13.png
  docs/src/administrator/guide/img/manage-user-14.png
  docs/src/administrator/guide/img/manage-user-15.png
  docs/src/administrator/guide/img/manage-user-2.png
  docs/src/administrator/guide/img/manage-user-3.png
  docs/src/administrator/guide/img/manage-user-4.png
  docs/src/administrator/guide/img/manage-user-5.png
  docs/src/administrator/guide/img/manage-user-6.png
  docs/src/administrator/guide/img/manage-user-7.png
  docs/src/administrator/guide/img/manage-user-8.png
  docs/src/administrator/guide/img/manage-user-9.png
  docs/src/administrator/guide/index.md
  docs/src/administrator/guide/manage-user.md
  docs/src/devops/guide/index.md
  docs/src/devops/index.md
  docs/src/devops/manual/index.md
Labels: documentation, 8

#108 Documentation contact us
  docs/mkdocs-base.yml
  docs/src/user/guide/contact-us.md
  docs/src/user/guide/img/contact-us-1.png
  docs/src/user/guide/img/contact-us-2.png
  docs/src/user/guide/img/contact-us-3.png
  docs/src/user/guide/img/contact-us-4.png
  docs/src/user/guide/index.md
  docs/src/user/manual/contact-us.md
  docs/src/user/manual/img/contact-us-1.png
  docs/src/user/manual/img/contact-us-2.png
  docs/src/user/manual/img/contact-us-3.png
  docs/src/user/manual/img/contact-us-4.png
  docs/src/user/manual/index.md
Labels: documentation, 3

#107 Administration organisation table guide
  docs/mkdocs-base.yml
  docs/src/administrator/guide/img/manage-organisation-1.png
  docs/src/administrator/guide/img/manage-organisation-10.png
  docs/src/administrator/guide/img/manage-organisation-11.png
  docs/src/administrator/guide/img/manage-organisation-12.png
  docs/src/administrator/guide/img/manage-organisation-13.png
  docs/src/administrator/guide/img/manage-organisation-14.png
  docs/src/administrator/guide/img/manage-organisation-15.png
  docs/src/administrator/guide/img/manage-organisation-16.png
  docs/src/administrator/guide/img/manage-organisation-17.png
  docs/src/administrator/guide/img/manage-organisation-18.png
  docs/src/administrator/guide/img/manage-organisation-19.png
  docs/src/administrator/guide/img/manage-organisation-2.png
  docs/src/administrator/guide/img/manage-organisation-20.png
  docs/src/administrator/guide/img/manage-organisation-21.png
  docs/src/administrator/guide/img/manage-organisation-22.png
  docs/src/administrator/guide/img/manage-organisation-23.png
  docs/src/administrator/guide/img/manage-organisation-3.png
  docs/src/administrator/guide/img/manage-organisation-4.png
  docs/src/administrator/guide/img/manage-organisation-5.png
  docs/src/administrator/guide/img/manage-organisation-6.png
  docs/src/administrator/guide/img/manage-organisation-7.png
  docs/src/administrator/guide/img/manage-organisation-8.png
  docs/src/administrator/guide/img/manage-organisation-9.png
  docs/src/administrator/guide/index.md
  docs/src/administrator/guide/manage-organisation.md
Labels: documentation, 5

#109 Documentation: Fix some build errors
  docs/mkdocs-base.yml
  docs/src/developer/documentation/index.md
  docs/src/user/guide/index.md
  docs/src/user/manual/index.md
Labels: documentation
